In [3]:
import numpy as np

In [14]:
state = 0
gamma = 0.9
lambda_ = 1.0
beta = 1.0
const = 1e-10
r = np.zeros(n_states)

n_states = 11
T = np.zeros((n_states, n_states))
T[0, 1:3] = 0.5
T[1, 3:5] = 0.5
T[2, 5:7] = 0.5
T[3, 7] = 1.0
T[4, 8] = 1.0
T[5, 9] = 1.0
T[6, 10] = 1.0
T[7:11, 7:11] = np.eye(4)
terminals =  np.diag(T) == 1
succ_states = np.where(T[state] > 0)[0]

D = np.eye(n_states)
print(D)
D[~terminals, :] = 1
print(D)
np.fill_diagonal(D, (1e-10+1 - gamma)**-1)
print(D)
print()

t = np.zeros(n_states-4) # P @ np.exp(r[terminals] / lambda_)
print(r)
print(t)
rmax = max(r[terminals])
# tmax = np.exp( rmax / lambda_)
t[3:] = np.exp( (r[terminals] - rmax) / lambda_)
print(t)
Z = np.zeros(n_states)
Z[~terminals] = (gamma * D[~terminals][:,~terminals]) @ t
Z[terminals] = t[3:]
Z[Z < const] = const  # prevent log(0)

log_Z = np.log(Z)            
log_Z += rmax / lambda_                   
V = log_Z[succ_states] * lambda_

V /= beta

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[9.99999999 1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.        ]
 [1.         9.99999999 1.         1.         1.         1.
  1.         1.         1.  

In [ ]:
Z[~terminals] = D[~terminals][:,~terminals] @ P @ expr_t
expr_t = np.exp(r[terminals] / _lambda)